p_saunders_test_homepage:
    path:     /
    defaults: { _controller: p_saunders_test.controller_default:indexAction }

p_saunders_test_about_us:
    path: /about-us
    defaults: { _controller: p_saunders_test.controller_default:aboutAction }